version: '3'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - tmp_vol:/tmp
      - ./Nginx/conf.d:/etc/nginx/conf.d
      - ./Nginx/static_pages:/usr/share/nginx/static_pages
      - ./eda-frontend/build:/usr/share/nginx/eda
      - ./ArduinoFrontend/dist:/usr/share/nginx/arduino-build
      - ./esim-cloud-backend/static:/usr/share/nginx/django_static
      - ./esim-cloud-backend/file_storage:/usr/share/nginx/django_file_storage
      - ./esim-cloud-backend/kicad-symbols/:/usr/share/nginx/kicad-libs
    depends_on:
      - django
      - eda-frontend
      - arduino-frontend

  eda-frontend:
    image: "docker.pkg.github.com/frg-fossee/esim-cloud/eda-frontend:master"
    build: ./eda-frontend/
    command: >
      sh -c "npm install &&
           npm run build"
    environment:
      - "PUBLIC_URL=${EDA_PUBLIC_URL}"
    volumes:
      - ./eda-frontend:/code



  arduino-frontend:
    image: "docker.pkg.github.com/frg-fossee/esim-cloud/arduino-frontend:master"
    build: ./ArduinoFrontend/
    command: >
      sh -c "npm install &&
             npm run ng -- build --prod --aot --base-href ${ARDUINO_BASE_HREF}"
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./ArduinoFrontend:/code



  django:
    image: "docker.pkg.github.com/frg-fossee/esim-cloud/django:master"
    build: ./esim-cloud-backend/
    command: >
      sh -c "gunicorn -w ${GUNICORN_WORKERS} --reload -b 0.0.0.0:8000 --log-level info esimCloud.wsgi"
    volumes:
      - ./esim-cloud-backend:/code
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    depends_on:
        - redis
        - db
        - celery
    env_file:
      - .env.prod
    environment:
      - DJANGO_DEBUG=True
    links:
      - "redis:redis"
      - "db:db"


  celery:
    image: "docker.pkg.github.com/frg-fossee/esim-cloud/celery:master"
    build: ./esim-cloud-backend/
    command: "celery -A esimCloud.celery worker -l info --concurrency=${CELERY_WORKERS}"
    links:
        - "redis:redis_cache"
        - "db:postgres"
        - "redis:redis"
        - "db:db"
    env_file:
          - .env.prod
    environment:
          - DJANGO_DEBUG=True
    volumes:
      - ./esim-cloud-backend:/code
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    depends_on:
      - redis
      - db
   
     

    deploy:
      replicas: 3

  redis:
      image: "redis:${TAG_REDIS}"
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      volumes:
          - ./redis_data:/data

  # Uncomment this and Change appropriate env variables to switch to mysql
  # db:
  #   image: "mysql:${TAG_MYSQL}"
  #   command: --default-authentication-plugin=mysql_native_password
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
